### PR TITLE
Abhi/connection properties

### PR DESCRIPTION
**Pull request by abhisheksinha89**
PR for
https://github.com/dbcli/mssql-cli/issues/118

### CODE REVIEW

**Comment by abhisheksinha89** [comment]
I'm currently brainstorming the best ideas to write tests for these connection params that does not involve setting up an actual live server with certs for encryption, etc.
Any suggestions welcome.

**Comment by abhisheksinha89** [comment]
I've only done manual testing, will not merge till I have unit tests for them

---
In reply to: [353253063](https://github.com/dbcli/mssql-cli/pull/126#issuecomment-353253063) [](ancestors = 353253063)

**Comment by MrMeemus** [comment]
@abhisheksinha89 , You could perhaps move the click decorators into their own module to make it modular for unit testing. Then you can use the CLI runner which is part of click.testing module to run through the options to ensure they are populated. That should verify the input aspect, then you can submit those options to the connection service contract and verify the format of the output.

For reference for click testing:
http://click.pocoo.org/5/testing/

Let me know if you thought of this already and found a issue with it.

**Comment by abhisheksinha89** [comment]
Talked with Brian, manual testing should be good for now as we are focused more on unblocking customers. I'll add an issue to write unit tests for command line params

---
In reply to: [353370093](https://github.com/dbcli/mssql-cli/pull/126#issuecomment-353370093) [](ancestors = 353370093)

**Pull request merged**
